CREATE TABLE IF NOT EXISTS USUARIOS_PERFIL (
    ID_USUARIO   UUID,
    ID_PERFIL    VARCHAR(10),
    DH_CRIACAO   TIMESTAMP DEFAULT NOW(),
    DH_ALTERACAO TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (ID_USUARIO, ID_PERFIL),
    CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ID_PERFIL FOREIGN KEY (ID_PERFIL) REFERENCES TIPOS_PERFIL_USUARIO(ID) ON DELETE CASCADE
);

COMMENT ON TABLE USUARIOS_PERFIL IS 'REGISTROS DE PERFIS RELACIONADOS AO USUÁRIO';
COMMENT ON COLUMN USUARIOS_PERFIL.ID_USUARIO IS 'IDENTIFICADOR ÚNICO DO USUÁRIO';
COMMENT ON COLUMN USUARIOS_PERFIL.ID_PERFIL IS 'IDENTIFICADOR ÚNICO DO PERFIL';
COMMENT ON COLUMN USUARIOS_PERFIL.DH_CRIACAO IS 'DATA E HORA DA CRIAÇÃO';
COMMENT ON COLUMN USUARIOS_PERFIL.DH_ALTERACAO IS 'DATA E HORA DA ULTIMA ALTERAÇÃO';


