CREATE TABLE IF NOT EXISTS SERVICOS (
    ID           UUID          DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    NOME         VARCHAR(100) UNIQUE,
    VALOR        NUMERIC(8, 2) DEFAULT 0,
    TEMPO        SMALLINT      DEFAULT 0,
    DISPONIVEL   BOOLEAN       DEFAULT TRUE,
    DH_CRIACAO   TIMESTAMP     DEFAULT NOW(),
    DH_ALTERACAO TIMESTAMP     DEFAULT NOW()
);

COMMENT ON TABLE SERVICOS IS 'REGISTRO DOS SERVIÇOS CADASTRADOS NO SISTEMA';
COMMENT ON COLUMN SERVICOS.ID IS 'IDENTIFICADOR ÚNICO';
COMMENT ON COLUMN SERVICOS.NOME IS 'NOME ÚNICO PARA O SERVIÇO';
COMMENT ON COLUMN SERVICOS.VALOR IS 'VALOR DO SERVIÇO';
COMMENT ON COLUMN SERVICOS.TEMPO IS 'TEMPO DO SERVIÇO EM MINUTOS';
COMMENT ON COLUMN SERVICOS.DH_CRIACAO IS 'DATA E HORA DA CRIAÇÃO';
COMMENT ON COLUMN SERVICOS.DH_ALTERACAO IS 'DATA E HORA DA ULTIMA ALTERAÇÃO';

