CREATE TABLE IF NOT EXISTS TIPOS_STATUS_ATENDIMENTO (
    ID           VARCHAR(4) PRIMARY KEY,
    NOME         VARCHAR(50) UNIQUE,
    DH_CRIACAO   TIMESTAMP DEFAULT NOW(),
    DH_ALTERACAO TIMESTAMP DEFAULT NOW()
);

COMMENT ON TABLE TIPOS_STATUS_ATENDIMENTO IS 'REGISTRO DOS TIPOS DE STATUS DE ATENDIMENTO CADASTRADOS NO SISTEMA';
COMMENT ON COLUMN TIPOS_STATUS_ATENDIMENTO.ID IS 'IDENTIFICADOR ÚNICO';
COMMENT ON COLUMN TIPOS_STATUS_ATENDIMENTO.NOME IS 'NOME ÚNICO PARA O STATUS';
COMMENT ON COLUMN TIPOS_STATUS_ATENDIMENTO.DH_CRIACAO IS 'DATA E HORA DA CRIAÇÃO';
COMMENT ON COLUMN TIPOS_STATUS_ATENDIMENTO.DH_ALTERACAO IS 'DATA E HORA DA ULTIMA ALTERAÇÃO';

INSERT INTO TIPOS_STATUS_ATENDIMENTO (ID, NOME)
VALUES ('AG', 'AGENDADO');

INSERT INTO TIPOS_STATUS_ATENDIMENTO (ID, NOME)
VALUES ('EA', 'EM ANDAMENTO');

INSERT INTO TIPOS_STATUS_ATENDIMENTO (ID, NOME)
VALUES ('CC', 'CONCLUÍDO');

INSERT INTO TIPOS_STATUS_ATENDIMENTO (ID, NOME)
VALUES ('CN', 'CANCELADO');

