CREATE TABLE IF NOT EXISTS TIPOS_STATUS_PAGAMENTO (
    ID           VARCHAR(4) PRIMARY KEY,
    NOME         VARCHAR(50) UNIQUE,
    DH_CRIACAO   TIMESTAMP DEFAULT NOW(),
    DH_ALTERACAO TIMESTAMP DEFAULT NOW()
);

COMMENT ON TABLE TIPOS_STATUS_PAGAMENTO IS 'REGISTRO DOS TIPOS DE STATUS DE PAGAMENTO CADASTRADOS NO SISTEMA';
COMMENT ON COLUMN TIPOS_STATUS_PAGAMENTO.ID IS 'IDENTIFICADOR ÚNICO';
COMMENT ON COLUMN TIPOS_STATUS_PAGAMENTO.NOME IS 'NOME ÚNICO PARA O STATUS';
COMMENT ON COLUMN TIPOS_STATUS_PAGAMENTO.DH_CRIACAO IS 'DATA E HORA DA CRIAÇÃO';
COMMENT ON COLUMN TIPOS_STATUS_PAGAMENTO.DH_ALTERACAO IS 'DATA E HORA DA ULTIMA ALTERAÇÃO';

INSERT INTO TIPOS_STATUS_PAGAMENTO (ID, NOME)
VALUES ('PG', 'PAGO');

INSERT INTO TIPOS_STATUS_PAGAMENTO (ID, NOME)
VALUES ('EA', 'EM ABERTO');

INSERT INTO TIPOS_STATUS_PAGAMENTO (ID, NOME)
VALUES ('CN', 'CANCELADO');

