CREATE TABLE IF NOT EXISTS TIPOS_METODO_PAGAMENTO (
    ID           VARCHAR(4) PRIMARY KEY,
    NOME         VARCHAR(50) UNIQUE,
    DH_CRIACAO   TIMESTAMP DEFAULT NOW(),
    DH_ALTERACAO TIMESTAMP DEFAULT NOW()
);

COMMENT ON TABLE TIPOS_METODO_PAGAMENTO IS 'REGISTRO DOS TIPOS DE METODOS DE PAGAMENTO CADASTRADOS NO SISTEMA';
COMMENT ON COLUMN TIPOS_METODO_PAGAMENTO.ID IS 'IDENTIFICADOR ÚNICO';
COMMENT ON COLUMN TIPOS_METODO_PAGAMENTO.NOME IS 'NOME ÚNICO PARA O MÉTODO';
COMMENT ON COLUMN TIPOS_METODO_PAGAMENTO.DH_CRIACAO IS 'DATA E HORA DA CRIAÇÃO';
COMMENT ON COLUMN TIPOS_METODO_PAGAMENTO.DH_ALTERACAO IS 'DATA E HORA DA ULTIMA ALTERAÇÃO';

INSERT INTO TIPOS_METODO_PAGAMENTO (ID, NOME)
VALUES ('DN', 'DINHEIRO');

INSERT INTO TIPOS_METODO_PAGAMENTO (ID, NOME)
VALUES ('PX', 'PIX');

INSERT INTO TIPOS_METODO_PAGAMENTO (ID, NOME)
VALUES ('CC', 'CARTÃO CRÉDITO');

INSERT INTO TIPOS_METODO_PAGAMENTO (ID, NOME)
VALUES ('CD', 'CARTÃO DÉBITO');

