server:
  port: 9001
  servlet:
    context-path: /sigbrb
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: sigbrb-backend

  datasource:
    url: ${PG_DB_URL}
    username: ${PG_DB_USERNAME}
    password: ${PG_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: SigBrbHikariCP

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate.format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

firebase:
  service-account:
    path: firebase/bsm-app-firebase-adminsdk.json
